# -*- coding: utf-8 -*-
"""DLProj_e1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J34xHArKAE9lGvfK-Fgyhskhwr3legxn

# imports
"""

import matplotlib.pyplot as plt
import os
import re

import string
import tensorflow as tf
from tensorflow.keras import regularizers

from tensorflow.keras import layers
from tensorflow.keras import losses

from collections import Counter


import pandas as pd
import numpy as np

if tf.test.gpu_device_name(): 
    print('Default GPU Device:{}'.format(tf.test.gpu_device_name()))

else:
    print("Please install GPU version of TF")

from google.colab import drive
drive.mount('/content/drive')

"""# Data"""

df_cor=pd.read_excel('/content/drive/MyDrive/DL_Pro/outputdf.xlsx')
df_ele=pd.read_excel('/content/drive/MyDrive/DL_Pro/outputdf1.xlsx')


df_cor.drop(columns=['url','published','published_utc','collection_utc','source','id','author','date'] , axis=1 , inplace=True)
df_ele.drop(columns=['url','published','published_utc','collection_utc','source','id','author','date'] , axis=1 , inplace=True)
df_cor = df_cor.loc[:, ~df_cor.columns.str.contains('^Unnamed')]
df_ele = df_ele.loc[:, ~df_ele.columns.str.contains('^Unnamed')]

print("shape of corona dataset = ",df_cor.shape)

print("shape of election dataset = ",df_ele.shape)

#set label for each datasets
df_cor['label'] = 0
df_ele['label'] = 1

df=pd.concat([df_cor,df_ele],ignore_index=True)       #concat two dataset
df=df.dropna()                                        #drop nan sampels
df = df.reset_index()
del df['index'] 
df = df.sample(frac=1).reset_index(drop=True)          #shafell data
print("shape of dataset = ",df.shape)
df.head()